### ISSUE TITLE
failed to mount CMEX CMSY

### ISSUE THREAD

**Issue by changephilip** [aligrudi/neatroff_make#3]
Hello,
I follow  instructions in README .
When I try "make" in demo directory,neatroff report :

> Generating test.ps
Generating test.pdf
Generating neatroff.ps
Generating neatroff.pdf
Generating neateqn.ps
neatroff: failed to mount \<CMEX\>
neatroff: failed to mount \<CMSY\>
neatroff: failed to mount \<CMEX\>
neatroff: failed to mount \<CMSY\>
Generating neateqn.pdf
Generating neatstart.ps
Generating neatstart.pdf
Generating neatcc.ps
Generating neatcc.pdf
rm neateqn.ps test.ps neatstart.ps neatcc.ps neatroff.ps

comment other make target and remain only neateqn.pdf, then neatroff report:
> Generating neateqn.ps
neatroff: failed to mount \<CMEX\>
neatroff: failed to mount \<CMSY\>
neatroff: failed to mount \<CMEX\>
neatroff: failed to mount \<CMSY\>
Generating neateqn.pdf
rm neateqn.ps

I check CMEX\CMSY font in fonts directory:
>ls fonts/CMEX10.* -lshta
12K -rw-rw-r-- 1 abc abc 9.8K Aug 14 17:08 ../fonts/CMEX10.afm
32K -rw-rw-r-- 1 abc abc  30K Jul 15  2009 ../fonts/CMEX10.pfb

and also found CMSY:
>ls fonts/CMSY10.* -lshta
12K -rw-rw-r-- 1 abc abc 8.8K Aug 14 17:08 ../fonts/CMSY10.afm
32K -rw-rw-r-- 1 abc abc  32K Jul 15  2009 ../fonts/CMSY10.pfb

If I comment follow lines, neatroff won't report "failed to mount":
>.fp - CMEX  Pxex
.fp - CMSY Pxsy

>.fp - CMEX txex
.fp - CMSY txsy

**Comment by aligrudi** [comment]
Hello,

changephilip <notifications@github.com> wrote:
> I follow  instructions in README .
> When I try "make" in demo directory,neatroff report :
> 
> comment other make target and remain only neateqn.pdf, then neatroff report:
> > Generating neateqn.ps
> neatroff: failed to mount <CMEX>
> neatroff: failed to mount <CMSY>
> neatroff: failed to mount <CMEX>
> neatroff: failed to mount <CMSY>
> Generating neateqn.pdf
> rm neateqn.ps
> 
> I check CMEX\CMSY font in fonts directory:
> >ls fonts/CMEX10.* -lshta
> 12K -rw-rw-r-- 1 abc abc 9.8K Aug 14 17:08 ../fonts/CMEX10.afm
> 32K -rw-rw-r-- 1 abc abc  30K Jul 15  2009 ../fonts/CMEX10.pfb
> 
> and also found CMSY:
> >ls fonts/CMSY10.* -lshta
> 12K -rw-rw-r-- 1 abc abc 8.8K Aug 14 17:08 ../fonts/CMSY10.afm
> 32K -rw-rw-r-- 1 abc abc  32K Jul 15  2009 ../fonts/CMSY10.pfb

These warnings are for mounting fonts from Pxfonts and Txfonts,
to CMEX and CMSY (CMSY10 and CMEX10 should be mounted without
problems; check the equations in the last page of neateqn.pdf):
  .fp - CMEX Pxex
  .fp - CMSY Pxsy

  .fp - CMEX txex
  .fp - CMSY txsy

I decided not to include these fonts, because they are
separately packaged:
https://www.ctan.org/tex-archive/fonts/pxfonts
https://www.ctan.org/tex-archive/fonts/txfonts

After copying the .afm and .pfb files to neatroff_make/fonts,
rebuild font descriptors with
  $ make neat
and rebuild neatroff_make/demo/neateqn.pdf
  $ cd demo && make clean all

Also note that fonts like pxex and pxsy have case problems;
the fonts are declared as Pxex and Pxsy in their .afm files
but their file names start with a lowercase letter.  You
need to rename pxsy.afm and pxsy.pfb to Pxsy.afm and Pxsy.pfb,
respectively (the same applies to pxex.afm and pxex.pfb).

	Ali

**Comment by changephilip** [comment]
@aligrudi 
Thank you!
